In [21]:
import pandas as pd

vol = pd.read_csv('stock_vol.csv')
vol['timestamp'] = pd.to_datetime(vol['timestamp'])
vol.fillna(0,inplace=True)
vol.loc[:, 'Cat10'] = vol.iloc[:, 1:11].apply(lambda x: x.argmax(), axis=1)
vol.loc[:, 'Cat2'] = [i[i.find('_')+1:] for i in vol.iloc[:, 1:11].apply(lambda x: x.argmax(), axis=1)]
print(vol.head())

            timestamp  120_before  60_before  30_before  10_before  5_before  \
0 2015-07-21 17:00:00    0.337179   0.136478   0.122044   0.018600  0.014314
1 2016-01-26 17:00:00    0.572057   0.262054   0.189982   0.069244  0.038341
2 2015-04-27 17:00:00    0.095532   0.078290   0.065764   0.044322  0.020542
3 2013-01-23 17:00:00    2.026954   0.505484   0.393379   0.352783  0.116103
4 2017-01-31 17:00:00    0.115896   0.072113   0.066953   0.027651  0.035514

    5_after  10_after  30_after  60_after  120_after ticker       Cat10  \
0  0.000000  0.000000   0.00000  0.000000   0.000000   AAPL  120_before
1  0.000000  0.000000   0.00000  0.000000   0.000000   AAPL  120_before
2  0.000000  0.000000   0.00000  0.000000   0.000000   AAPL  120_before
3  1.482074  1.971758   3.24086  3.319615   2.806857   AAPL    60_after
4  0.000000  0.000000   0.00000  0.000000   0.000000   AAPL  120_before

     Cat2
0  before
1  before
2  before
3   after
4  before

In [22]:
sent = pd.read_csv('18.csv')
sent.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ticker</th>
      <th>year</th>
      <th>quarter</th>
      <th>date</th>
      <th>time</th>
      <th>Anger</th>
      <th>Disgust</th>
      <th>Fear</th>
      <th>Joy</th>
      <th>Sadness</th>
      <th>Analytical</th>
      <th>Confident</th>
      <th>Tentative</th>
      <th>Openness</th>
      <th>Conscientiousness</th>
      <th>Extraversion</th>
      <th>Agreeableness</th>
      <th>Emotional Range</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>BPOP</td>
      <td>2011</td>
      <td>2</td>
      <td>7/20/2011</td>
      <td>2:00 pm</td>
      <td>0.150605</td>
      <td>0.134367</td>
      <td>0.148578</td>
      <td>0.587512</td>
      <td>0.565885</td>
      <td>0.000000</td>
      <td>0.0</td>
      <td>0.765529</td>
      <td>0.424949</td>
      <td>0.799928</td>
      <td>0.745411</td>
      <td>0.681134</td>
      <td>0.834028</td>
    </tr>
    <tr>
      <th>1</th>
      <td>BPOP</td>
      <td>2011</td>
      <td>3</td>
      <td>10/19/2011</td>
      <td>8:00 AM</td>
      <td>0.187803</td>
      <td>0.128904</td>
      <td>0.144734</td>
      <td>0.568294</td>
      <td>0.545904</td>
      <td>0.000000</td>
      <td>0.0</td>
      <td>0.661890</td>
      <td>0.378921</td>
      <td>0.867867</td>
      <td>0.721122</td>
      <td>0.589329</td>
      <td>0.861265</td>
    </tr>
    <tr>
      <th>2</th>
      <td>BPOP</td>
      <td>2012</td>
      <td>4</td>
      <td>1/25/2011</td>
      <td>10:30 AM</td>
      <td>0.465452</td>
      <td>0.151029</td>
      <td>0.157758</td>
      <td>0.556769</td>
      <td>0.550603</td>
      <td>0.743424</td>
      <td>0.0</td>
      <td>0.252584</td>
      <td>0.229526</td>
      <td>0.858134</td>
      <td>0.595939</td>
      <td>0.610012</td>
      <td>0.843461</td>
    </tr>
    <tr>
      <th>3</th>
      <td>BPOP</td>
      <td>2012</td>
      <td>1</td>
      <td>4/20/2012</td>
      <td>10:30 AM</td>
      <td>0.163041</td>
      <td>0.145653</td>
      <td>0.134882</td>
      <td>0.587176</td>
      <td>0.522257</td>
      <td>0.714602</td>
      <td>0.0</td>
      <td>0.104199</td>
      <td>0.325208</td>
      <td>0.967353</td>
      <td>0.824072</td>
      <td>0.822331</td>
      <td>0.861568</td>
    </tr>
    <tr>
      <th>4</th>
      <td>BPOP</td>
      <td>2012</td>
      <td>2</td>
      <td>7/18/2012</td>
      <td>10:30 AM</td>
      <td>0.177125</td>
      <td>0.135790</td>
      <td>0.153001</td>
      <td>0.589258</td>
      <td>0.501145</td>
      <td>0.000000</td>
      <td>0.0</td>
      <td>0.607670</td>
      <td>0.349026</td>
      <td>0.894523</td>
      <td>0.798674</td>
      <td>0.659148</td>
      <td>0.806333</td>
    </tr>
  </tbody>
</table>
</div>

In [23]:
sent["timestamp"] = pd.to_datetime(sent['date'] + ' ' + sent['time'])

In [24]:
df = pd.merge(vol, sent, how='left', on=['ticker', 'timestamp'])
df.to_csv('final_result.csv')