In [2]:
import pandas as pd

#vol = pd.read_csv('stock_price.csv')
vol = pd.read_csv('avg_price.csv')
vol['timestamp'] = pd.to_datetime(vol['timestamp'])
vol.fillna(0,inplace=True)
vol.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>timestamp</th>
      <th>-120</th>
      <th>-119</th>
      <th>-118</th>
      <th>-117</th>
      <th>-116</th>
      <th>-115</th>
      <th>-114</th>
      <th>-113</th>
      <th>-112</th>
      <th>...</th>
      <th>112</th>
      <th>113</th>
      <th>114</th>
      <th>115</th>
      <th>116</th>
      <th>117</th>
      <th>118</th>
      <th>119</th>
      <th>120</th>
      <th>ticker</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2012-07-24 17:00:00</td>
      <td>0.0</td>
      <td>-0.024010</td>
      <td>-0.023996</td>
      <td>-0.023982</td>
      <td>-0.023963</td>
      <td>-0.023941</td>
      <td>-0.023917</td>
      <td>-0.023906</td>
      <td>-0.023896</td>
      <td>...</td>
      <td>-0.022134</td>
      <td>-0.022139</td>
      <td>-0.022153</td>
      <td>-0.022167</td>
      <td>-0.022178</td>
      <td>-0.022189</td>
      <td>-0.022206</td>
      <td>-0.022225</td>
      <td>0.0</td>
      <td>AAPL</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2013-04-23 17:00:00</td>
      <td>0.0</td>
      <td>-0.015150</td>
      <td>-0.015148</td>
      <td>-0.015146</td>
      <td>-0.015149</td>
      <td>-0.015154</td>
      <td>-0.015155</td>
      <td>-0.015156</td>
      <td>-0.015158</td>
      <td>...</td>
      <td>0.007317</td>
      <td>0.007321</td>
      <td>0.007313</td>
      <td>0.007300</td>
      <td>0.007274</td>
      <td>0.007259</td>
      <td>0.007240</td>
      <td>0.007214</td>
      <td>0.0</td>
      <td>AAPL</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2011-10-18 17:00:00</td>
      <td>0.0</td>
      <td>-0.024765</td>
      <td>-0.024781</td>
      <td>-0.024799</td>
      <td>-0.024815</td>
      <td>-0.024827</td>
      <td>-0.024847</td>
      <td>-0.024867</td>
      <td>-0.024894</td>
      <td>...</td>
      <td>-0.020787</td>
      <td>-0.020712</td>
      <td>-0.020633</td>
      <td>-0.020541</td>
      <td>-0.020441</td>
      <td>-0.020338</td>
      <td>-0.020234</td>
      <td>-0.020142</td>
      <td>0.0</td>
      <td>AAPL</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2013-01-23 17:00:00</td>
      <td>0.0</td>
      <td>-0.051228</td>
      <td>-0.051263</td>
      <td>-0.051303</td>
      <td>-0.051347</td>
      <td>-0.051393</td>
      <td>-0.051445</td>
      <td>-0.051504</td>
      <td>-0.051561</td>
      <td>...</td>
      <td>-0.051718</td>
      <td>-0.051723</td>
      <td>-0.051725</td>
      <td>-0.051717</td>
      <td>-0.051714</td>
      <td>-0.051704</td>
      <td>-0.051686</td>
      <td>-0.051663</td>
      <td>0.0</td>
      <td>AAPL</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2012-01-24 17:00:00</td>
      <td>0.0</td>
      <td>0.034846</td>
      <td>0.034853</td>
      <td>0.034867</td>
      <td>0.034890</td>
      <td>0.034906</td>
      <td>0.034925</td>
      <td>0.034942</td>
      <td>0.034960</td>
      <td>...</td>
      <td>0.025248</td>
      <td>0.025270</td>
      <td>0.025300</td>
      <td>0.025333</td>
      <td>0.025362</td>
      <td>0.025384</td>
      <td>0.025411</td>
      <td>0.025437</td>
      <td>0.0</td>
      <td>AAPL</td>
    </tr>
  </tbody>
</table>
<p>5 rows Ã— 243 columns</p>
</div>

In [10]:
#vol.loc[:, 'Cat10'] = vol.iloc[:, 1:11].apply(lambda x: x.argmax(), axis=1)

vol.loc[:, 'before'] = vol.iloc[:, 1:6].mean(axis=1)
vol.loc[:, 'after'] = vol.iloc[:, 5:11].mean(axis=1)

price = vol.copy()

price.loc[vol.before <= 0, 'before'] = 'D'
price.loc[vol.before > 0, 'before'] = 'U'
price.loc[vol.after <= 0, 'after'] = 'D'
price.loc[vol.after > 0, 'after'] = 'U'

price.loc[:, 'Cat'] = price.loc[:, ['before', 'after']].apply(lambda x: ''.join(x), axis=1)

print(price.head())

            timestamp  120_before  60_before  30_before  10_before  5_before  \
0 2013-04-23 17:00:00    0.000739   0.001602  -0.003196  -0.003981 -0.000517
1 2016-10-25 17:00:00    0.000859   0.001276   0.001531   0.000893  0.000298
2 2012-04-24 17:00:00    0.008644  -0.003937  -0.000889   0.001518 -0.000089
3 2013-07-23 17:00:00   -0.009856  -0.008816  -0.004239  -0.001026  0.000239
4 2014-04-23 17:00:00   -0.001134   0.000454  -0.000178  -0.000511 -0.000397

    5_after  10_after  30_after  60_after  120_after ticker before after Cat
0  0.012327  0.025272  0.038639  0.021734        0.0   AAPL      D     U  DU
1  0.000000  0.000000  0.000000  0.000000        0.0   AAPL      U     U  UU
2 -0.012674 -0.004119  0.004263 -0.002951        0.0   AAPL      U     D  UD
3 -0.001234 -0.000546 -0.002283  0.004487        0.0   AAPL      D     U  DU
4  0.000000  0.000000  0.000000  0.000000        0.0   AAPL      D     D  DD

In [3]:
sent = pd.read_csv('19.csv')
sent.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>ticker</th>
      <th>timestamp</th>
      <th>120_before_vol</th>
      <th>60_before_vol</th>
      <th>30_before_vol</th>
      <th>10_before_vol</th>
      <th>5_before_vol</th>
      <th>5_after_vol</th>
      <th>10_after_vol</th>
      <th>30_after_vol</th>
      <th>...</th>
      <th>Analytical</th>
      <th>Confident</th>
      <th>Tentative</th>
      <th>Openness</th>
      <th>Conscientiousness</th>
      <th>Extraversion</th>
      <th>Agreeableness</th>
      <th>Emotional Range</th>
      <th>Cat10</th>
      <th>Cat2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>AAPL</td>
      <td>7/21/15 17:00</td>
      <td>0.337179</td>
      <td>0.136478</td>
      <td>0.122044</td>
      <td>0.018600</td>
      <td>0.014314</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>...</td>
      <td>0.729482</td>
      <td>0.0</td>
      <td>0.305310</td>
      <td>0.522968</td>
      <td>0.763873</td>
      <td>0.827263</td>
      <td>0.720570</td>
      <td>0.786474</td>
      <td>120_before</td>
      <td>before</td>
    </tr>
    <tr>
      <th>1</th>
      <td>AAPL</td>
      <td>1/26/16 17:00</td>
      <td>0.572057</td>
      <td>0.262054</td>
      <td>0.189982</td>
      <td>0.069244</td>
      <td>0.038341</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>...</td>
      <td>0.706643</td>
      <td>0.0</td>
      <td>0.486052</td>
      <td>0.477063</td>
      <td>0.716117</td>
      <td>0.793926</td>
      <td>0.676473</td>
      <td>0.645176</td>
      <td>120_before</td>
      <td>before</td>
    </tr>
    <tr>
      <th>2</th>
      <td>AAPL</td>
      <td>4/27/15 17:00</td>
      <td>0.095532</td>
      <td>0.078290</td>
      <td>0.065764</td>
      <td>0.044322</td>
      <td>0.020542</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>...</td>
      <td>0.207012</td>
      <td>0.0</td>
      <td>0.076346</td>
      <td>0.249613</td>
      <td>0.634723</td>
      <td>0.701370</td>
      <td>0.711850</td>
      <td>0.657607</td>
      <td>120_before</td>
      <td>before</td>
    </tr>
    <tr>
      <th>3</th>
      <td>AAPL</td>
      <td>1/23/13 17:00</td>
      <td>2.026954</td>
      <td>0.505484</td>
      <td>0.393379</td>
      <td>0.352783</td>
      <td>0.116103</td>
      <td>1.482074</td>
      <td>1.971758</td>
      <td>3.24086</td>
      <td>...</td>
      <td>0.558772</td>
      <td>0.0</td>
      <td>0.079063</td>
      <td>0.487331</td>
      <td>0.925340</td>
      <td>0.772834</td>
      <td>0.689951</td>
      <td>0.793277</td>
      <td>60_after</td>
      <td>after</td>
    </tr>
    <tr>
      <th>4</th>
      <td>AAPL</td>
      <td>1/31/17 17:00</td>
      <td>0.115896</td>
      <td>0.072113</td>
      <td>0.066953</td>
      <td>0.027651</td>
      <td>0.035514</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>...</td>
      <td>0.662148</td>
      <td>0.0</td>
      <td>0.158698</td>
      <td>0.501163</td>
      <td>0.863210</td>
      <td>0.799753</td>
      <td>0.678468</td>
      <td>0.847058</td>
      <td>120_before</td>
      <td>before</td>
    </tr>
  </tbody>
</table>
<p>5 rows Ã— 27 columns</p>
</div>

In [4]:
sent["timestamp"] = pd.to_datetime(sent["timestamp"])   #sent['date'] + ' ' + sent['time'])

In [5]:
df = pd.merge(price, sent, how='left', on=['ticker', 'timestamp'])
df.to_csv('avg_price_merged.csv')

NameError: name 'price' is not defined